### ISSUE TITLE
Ryan is clueless?

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-Ryanyzh#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-Ryanyzh/blob/7e8f9b4646e8e916791b0758c25e277e893f461a/app/src/main/java/sg/edu/np/mad/s10219317_ryanyong/MainActivity.java#L11-L17

You can check with me if you are clueless

You just missing initialising the textviews with your user object

And your scrollview doesnt work right?

**Comment by Ryanyzh** [comment]
Oh... the clueless part was just the description hahahahaha. I have also added in the missing initialization and the scroll view.
